#include <stddef.h>

void* js_call() { return NULL; }
void* js_copy() { return NULL; }
void* js_currentfunction() { return NULL; }
void* js_defproperty() { return NULL; }
void* js_endtry() { return NULL; }
void* js_error() { return NULL; }
void* js_freestate() { return NULL; }
void* js_gc() { return NULL; }
void* js_getcontext() { return NULL; }
void* js_getglobal() { return NULL; }
void* js_getindex() { return NULL; }
void* js_getlength() { return NULL; }
void* js_getproperty() { return NULL; }
void* js_gettop() { return NULL; }
void* js_hasproperty() { return NULL; }
void* js_isarray() { return NULL; }
void* js_isboolean() { return NULL; }
void* js_iscallable() { return NULL; }
void* js_isnull() { return NULL; }
void* js_isnumber() { return NULL; }
void* js_isobject() { return NULL; }
void* js_isundefined() { return NULL; }
void* js_loadstring() { return NULL; }
void* js_newarray() { return NULL; }
void* js_newcfunction() { return NULL; }
void* js_newobject() { return NULL; }
void* js_newregexp() { return NULL; }
void* js_newstate() { return NULL; }
void* js_newuserdata() { return NULL; }
void* js_nextiterator() { return NULL; }
void* js_pcall() { return NULL; }
void* js_pop() { return NULL; }
void* js_pushboolean() { return NULL; }
void* js_pushglobal() { return NULL; }
void* js_pushiterator() { return NULL; }
void* js_pushlstring() { return NULL; }
void* js_pushnull() { return NULL; }
void* js_pushnumber() { return NULL; }
void* js_pushstring() { return NULL; }
void* js_pushundefined() { return NULL; }
void* js_rot2() { return NULL; }
void* js_savetry() { return NULL; }
void* js_setcontext() { return NULL; }
void* js_setglobal() { return NULL; }
void* js_setindex() { return NULL; }
void* js_setproperty() { return NULL; }
void* js_setreport() { return NULL; }
void* js_throw() { return NULL; }
void* js_toboolean() { return NULL; }
void* js_tonumber() { return NULL; }
void* js_tostring() { return NULL; }
void* js_touserdata() { return NULL; }
void* js_trystring() { return NULL; }
