#include <stddef.h>

void* lua_call() { return NULL; }
void* lua_close() { return NULL; }
void* lua_cpcall() { return NULL; }
void* lua_createtable() { return NULL; }
void* lua_error() { return NULL; }
void* lua_getallocf() { return NULL; }
void* lua_getfield() { return NULL; }
void* lua_getmetatable() { return NULL; }
void* lua_gettable() { return NULL; }
void* lua_gettop() { return NULL; }
void* lua_insert() { return NULL; }
void* luaL_checkinteger() { return NULL; }
void* luaL_checklstring() { return NULL; }
void* luaL_checknumber() { return NULL; }
void* luaL_checkoption() { return NULL; }
void* luaL_checkstack() { return NULL; }
void* luaL_error() { return NULL; }
void* luaL_loadbuffer() { return NULL; }
void* luaL_loadstring() { return NULL; }
void* luaL_newstate() { return NULL; }
void* luaL_openlibs() { return NULL; }
void* luaL_optlstring() { return NULL; }
void* luaL_optnumber() { return NULL; }
void* lua_next() { return NULL; }
void* lua_pcall() { return NULL; }
void* lua_pushboolean() { return NULL; }
void* lua_pushcclosure() { return NULL; }
void* lua_pushinteger() { return NULL; }
void* lua_pushlightuserdata() { return NULL; }
void* lua_pushlstring() { return NULL; }
void* lua_pushnil() { return NULL; }
void* lua_pushnumber() { return NULL; }
void* lua_pushstring() { return NULL; }
void* lua_pushvalue() { return NULL; }
void* lua_rawset() { return NULL; }
void* lua_rawseti() { return NULL; }
void* lua_remove() { return NULL; }
void* lua_setallocf() { return NULL; }
void* lua_setfield() { return NULL; }
void* lua_setmetatable() { return NULL; }
void* lua_settable() { return NULL; }
void* lua_settop() { return NULL; }
void* lua_toboolean() { return NULL; }
void* lua_tolstring() { return NULL; }
void* lua_tonumber() { return NULL; }
void* lua_touserdata() { return NULL; }
void* lua_type() { return NULL; }
void* lua_typename() { return NULL; }
