# Seed ephemeral Flutter Linux artifacts from the engine cache when missing.
# Invoked AFTER flutter_assemble (Distrobox often leaves ephemeral incomplete).
if(FLUTTER_ROOT STREQUAL "" OR EPHEMERAL_DIR STREQUAL "")
  message(FATAL_ERROR "seed_flutter_linux.cmake requires FLUTTER_ROOT and EPHEMERAL_DIR")
endif()

if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE "Debug")
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Release")
  set(_engine_variant "linux-x64-release")
elseif(CMAKE_BUILD_TYPE STREQUAL "Profile")
  set(_engine_variant "linux-x64-profile")
else()
  set(_engine_variant "linux-x64")
endif()

set(_engine_root "${FLUTTER_ROOT}/bin/cache/artifacts/engine")
set(_hdr "${EPHEMERAL_DIR}/flutter_linux/flutter_linux.h")
set(_hdr_src "${_engine_root}/linux-x64/flutter_linux")
set(_so_dst "${EPHEMERAL_DIR}/libflutter_linux_gtk.so")
set(_so_src "${_engine_root}/${_engine_variant}/libflutter_linux_gtk.so")
set(_icu_dst "${EPHEMERAL_DIR}/icudtl.dat")
set(_icu_src "${_engine_root}/linux-x64/icudtl.dat")

if(NOT EXISTS "${_hdr}")
  if(NOT EXISTS "${_hdr_src}/flutter_linux.h")
    message(FATAL_ERROR "Engine flutter_linux headers missing at ${_hdr_src}")
  endif()
  file(MAKE_DIRECTORY "${EPHEMERAL_DIR}/flutter_linux")
  file(COPY "${_hdr_src}/" DESTINATION "${EPHEMERAL_DIR}/flutter_linux")
  if(NOT EXISTS "${_hdr}")
    message(FATAL_ERROR "Failed to seed flutter_linux.h into ${EPHEMERAL_DIR}/flutter_linux")
  endif()
  message(STATUS "Seeded flutter_linux headers from engine cache")
endif()

if(NOT EXISTS "${_so_dst}")
  if(NOT EXISTS "${_so_src}")
    message(FATAL_ERROR "Engine libflutter_linux_gtk.so missing at ${_so_src}")
  endif()
  file(COPY "${_so_src}" DESTINATION "${EPHEMERAL_DIR}")
  if(NOT EXISTS "${_so_dst}")
    message(FATAL_ERROR "Failed to seed libflutter_linux_gtk.so into ${EPHEMERAL_DIR}")
  endif()
  message(STATUS "Seeded libflutter_linux_gtk.so (${_engine_variant})")
endif()

if(NOT EXISTS "${_icu_dst}")
  if(EXISTS "${_icu_src}")
    file(COPY "${_icu_src}" DESTINATION "${EPHEMERAL_DIR}")
    message(STATUS "Seeded icudtl.dat from engine cache")
  endif()
endif()
